spring:
  datasource:
    url: jdbc:h2:mem:testdb
    spring.datasource.driverClassName: org.h2.Driver
    spring.datasource.username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
